In [12]:
from game_one.model_cfm_train import CFMTrain
test =  CFMTrain()
CFMTrain.load_data(test)
CFMTrain.get_ratings_and_meta(test)

/Users/guillaume/.pyenv/versions/3.8.6/envs/game_one_ðŸ‘¾/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3347: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
/Users/guillaume/code/Agnes-Lain/game_one/game_one/model_cfm_train.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['dummies'] = 0

(        user_id  game_id  user_rating
 0             1   446900            4
 1             1   264830            5
 2             1    58443            4
 4             1    21889            4
 5             1     1190            4
 ...         ...      ...          ...
 255492  rasha27     5578            5
 255493  rasha27   326292            3
 255494  rasha27     2572            5
 255495  rasha27     4003            5
 255496  rasha27     3272            5

 [24505 rows x 3 columns],
       game_id                                        game_name    released  \
 0           2                                 Extreme Exorcism  2015-09-23
 1           4                                         Penarium  2015-09-22
 2          12                                         Ironcast  2015-03-26
 3          14                                 Tetrobot and Co.  2013-10-15
 4          15                              Gryphon Knight Epic  2015-08-20
 ...       ...                                              ...         ...
 3899   518596                    Nioh 2 â€“ The Complete Edition  2021-02-05
 3900   520300  Atelier Ryza 2: Lost Legends & the Secret Fairy  2021-01-26
 3901   527389                      ArcaniA - The Complete Tale  2013-07-15
 3902   528768                               Persona 5 Strikers  2020-02-20
 3903   545028                     Brigador: Up-Armored Edition  2016-06-02

       metacritic  rawg_rating
 0           75.0         2.77
 1           80.0         3.20
 2           75.0         3.50
 3           72.0         3.70
 4           55.0         0.00
 ...          ...          ...
 3899        88.0         0.00
 3900        80.0         0.00
 3901        42.0         0.00
 3902        81.0         4.12
 3903        70.0         2.14

 [3904 rows x 5 columns])

In [ ]:
compute_df = test.data
compute_df

In [18]:
filter_df = compute_df[compute_df['user_rating']>0]
filter_df

,user_id,game_id,game_slug,game_name,user_rating,metacritic,rawg_rating,released,play_time,purchase,dummies
0,1,446900,high-rise-a-puzzle-cityscape,High Rise - A Puzzle Cityscape,4,NaN,0.00,2020-05-16,0,1,0
1,1,264830,twinfold,Twinfold,5,NaN,0.00,2018-12-05,0,1,0
2,1,58443,pocket-run-pool,Pocket-Run Pool,4,NaN,0.00,2018-05-24,0,1,0
4,1,21889,desert-fox-the-battle-of-el-alamein,Desert Fox: The Battle of El Alamein,4,NaN,0.00,2014-06-26,0,1,0
5,1,1190,imbroglio,Imbroglio,4,NaN,0.00,2016-05-18,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
255492,rasha27,5578,grid,Race Driver: Grid,5,87.0,3.67,2008-06-03,1,1,0
255493,rasha27,326292,fall-guys,Fall Guys: Ultimate Knockout,3,80.0,3.87,2020-08-04,4,1,0
255494,rasha27,2572,dirt-rally,DiRT Rally,5,86.0,3.74,2015-12-07,4,1,0
255495,rasha27,4003,grid-2,GRID 2,5,80.0,3.30,2013-05-27,4,1,0
255496,rasha27,3272,rocket-league,Rocket League,5,86.0,4.01,2015-07-07,17,1,0

In [22]:
filter_df[filter_df['game_id']==58443]

,user_id,game_id,game_slug,game_name,user_rating,metacritic,rawg_rating,released,play_time,purchase,dummies
2,1,58443,pocket-run-pool,Pocket-Run Pool,4,NaN,0.0,2018-05-24,0,1,0

In [25]:
if filter_df['rawg_rating'][0] == 4.0

4.0

In [29]:
list(filter_df.index)

[0,
 1,
 2,
 4,
 5,
 6,
 7,
 9,
 10,
 11,
 12,
 13,
 15,
 16,
 17,
 19,
 20,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 35,
 37,
 38,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 51,
 53,
 55,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 72,
 73,
 75,
 76,
 77,
 78,
 80,
 82,
 83,
 84,
 86,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 98,
 99,
 100,
 102,
 103,
 104,
 105,
 106,
 107,
 109,
 111,
 112,
 113,
 114,
 115,
 116,
 118,
 119,
 120,
 121,
 123,
 124,
 125,
 126,
 127,
 128,
 130,
 133,
 134,
 136,
 137,
 138,
 139,
 140,
 141,
 143,
 145,
 146,
 148,
 150,
 152,
 153,
 154,
 156,
 158,
 161,
 166,
 170,
 171,
 173,
 176,
 177,
 179,
 183,
 184,
 185,
 187,
 188,
 191,
 192,
 195,
 196,
 197,
 199,
 200,
 201,
 207,
 208,
 212,
 214,
 216,
 217,
 222,
 224,
 225,
 227,
 228,
 229,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 239,
 241,
 242,
 243,
 244,
 246,
 247,
 248,
 250,
 251,
 252,
 257,
 258,
 259,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 272,
 273,
 274,
 275,
 276,
 278,
 280,
 285,
 287,
 289,
 291,
 292,
 293,
 294,
 295,
 296,
 298,
 300,
 302,
 303,
 304,
 306,
 307,
 308,
 309,
 312,
 313,
 314,
 315,
 317,
 320,
 321,
 323,
 324,
 326,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 336,
 337,
 340,
 342,
 345,
 346,
 347,
 349,
 352,
 353,
 355,
 357,
 358,
 360,
 365,
 366,
 367,
 369,
 370,
 371,
 373,
 374,
 375,
 376,
 377,
 379,
 380,
 381,
 382,
 383,
 384,
 386,
 387,
 388,
 389,
 391,
 392,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 407,
 408,
 410,
 411,
 412,
 413,
 415,
 416,
 418,
 419,
 421,
 422,
 423,
 424,
 425,
 427,
 430,
 431,
 432,
 433,
 434,
 436,
 438,
 439,
 440,
 441,
 443,
 444,
 445,
 448,
 449,
 450,
 451,
 452,
 456,
 457,
 458,
 459,
 462,
 464,
 465,
 466,
 468,
 469,
 471,
 472,
 474,
 475,
 476,
 477,
 478,
 479,
 481,
 483,
 487,
 488,
 489,
 490,
 495,
 497,
 498,
 499,
 500,
 503,
 506,
 510,
 511,
 512,
 513,
 515,
 518,
 520,
 521,
 525,
 526,
 527,
 531,
 532,
 533,
 535,
 538,
 540,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 556,
 557,
 559,
 560,
 561,
 563,
 564,
 565,
 566,
 567,
 569,
 570,
 571,
 573,
 575,
 576,
 577,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 592,
 593,
 595,
 598,
 600,
 602,
 603,
 604,
 605,
 606,
 607,
 610,
 612,
 613,
 614,
 615,
 616,
 619,
 621,
 622,
 623,
 624,
 625,
 627,
 628,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 638,
 639,
 640,
 642,
 643,
 644,
 645,
 646,
 647,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 677,
 678,
 679,
 680,
 681,
 707,
 708,
 709,
 710,
 711,
 712,
 715,
 716,
 720,
 721,
 722,
 724,
 725,
 726,
 727,
 729,
 730,
 731,
 732,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 752,
 753,
 754,
 756,
 757,
 759,
 760,
 761,
 762,
 763,
 765,
 766,
 767,
 770,
 772,
 773,
 774,
 776,
 778,
 779,
 780,
 781,
 783,
 784,
 785,
 786,
 789,
 790,
 792,
 794,
 795,
 796,
 797,
 798,
 799,
 802,
 803,
 805,
 807,
 808,
 809,
 810,
 812,
 813,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 825,
 829,
 830,
 832,
 835,
 836,
 837,
 838,
 840,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 851,
 853,
 854,
 855,
 856,
 857,
 860,
 862,
 863,
 864,
 866,
 868,
 869,
 870,
 871,
 873,
 874,
 875,
 876,
 877,
 878,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 892,
 893,
 894,
 896,
 897,
 898,
 899,
 900,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 911,
 912,
 913,
 914,
 915,
 916,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 927,
 928,
 929,
 931,
 932,
 934,
 935,
 936,
 937,
 940,
 942,
 945,
 947,
 949,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 962,
 963,
 964,
 965,
 966,
 967,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 978,
 979,
 982,
 983,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 998,
 999,
 1001,
 1003,
 1004,
 1005,
 1008,
 1009,
 1010,
 1013,
 1016,
 1017,
 1019,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1028,
 1029,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1038,
 1039,
 1041,
 1042,
 1043,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1060,
 1062,
 1063,
 1064,
 1065,
 1066,
 1068,
 1069,
 1070,
 1071,
 1073,
 1074,
 1075,
 1077,
 1078,
 1079,
 1080,
 1081,
 1083,
 1087,
 1088,
 1090,
 1094,
 1096,
 1101,
 1104,
 1106,
 1108,
 1110,
 1112,
 1114,
 1115,
 1117,
 1118,
 1119,
 1121,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1130,
 1133,
 1134,
 1135,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1148,
 1149,
 1152,
 1153,
 1154,
 1155,
 1156,
 1158,
 1159,
 1161,
 1162,
 1164,
 1165,
 1166,
 1167,
 1170,
 1179,
 1181,
 1183,
 1185,
 1190,
 1207,
 1209,
 1213,
 1214,
 1218,
 1223,
 1226,
 1231,
 1232,
 1233,
 1235,
 1236,
 1238,
 1239,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1246,
 1247,
 1249,
 1252,
 1254,
 1255,
 1256,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1266,
 1267,
 1268,
 1270,
 1271,
 1274,
 1275,
 1277,
 1279,
 1280,
 1285,
 1286,
 1288,
 1289,
 1290,
 1292,
 1293,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1301,
 1303,
 1306,
 1307,
 1308,
 1310,
 1314,
 1318,
 1322,
 1324,
 1328,
 1329,
 1330,
 1333,
 1335,
 1336,
 1337,
 1338,
 1339,
 1341,
 1342,
 1343,
 1345,
 1347,
 1350,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1362,
 1363,
 1364,
 1368,
 1369,
 1370,
 1371,
 1372,
 1374,
 1376,
 1377,
 1378,
 1379,
 1380,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1401,
 1402,
 1403,
 1404,
 1405,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1420,
 1421,
 1422,
 1423,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1433,
 1435,
 1436,
 1437,
 1438,
 1439,
 1441,
 1445,
 1447,
 1448,
 1450,
 1452,
 1453,
 1454,
 1455,
 1457,
 1460,
 1461,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1470,
 1471,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1480,
 1481,
 1482,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1492,
 1493,
 1495,
 1496,
 1497,
 1498,
 1500,
 1503,
 1506,
 ...]

In [30]:
for index in list(filter_df.index):
    if filter_df['rawg_rating'][index] == 0.0:
        filter_df['rawg_rating'][index] = filter_df['user_rating'][index]

<ipython-input-30-4d2f90aa4c4b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['rawg_rating'][index] = filter_df['user_rating'][index]

In [31]:
filter_df

,user_id,game_id,game_slug,game_name,user_rating,metacritic,rawg_rating,released,play_time,purchase,dummies
0,1,446900,high-rise-a-puzzle-cityscape,High Rise - A Puzzle Cityscape,4,NaN,4.00,2020-05-16,0,1,0
1,1,264830,twinfold,Twinfold,5,NaN,5.00,2018-12-05,0,1,0
2,1,58443,pocket-run-pool,Pocket-Run Pool,4,NaN,4.00,2018-05-24,0,1,0
4,1,21889,desert-fox-the-battle-of-el-alamein,Desert Fox: The Battle of El Alamein,4,NaN,4.00,2014-06-26,0,1,0
5,1,1190,imbroglio,Imbroglio,4,NaN,4.00,2016-05-18,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
255492,rasha27,5578,grid,Race Driver: Grid,5,87.0,3.67,2008-06-03,1,1,0
255493,rasha27,326292,fall-guys,Fall Guys: Ultimate Knockout,3,80.0,3.87,2020-08-04,4,1,0
255494,rasha27,2572,dirt-rally,DiRT Rally,5,86.0,3.74,2015-12-07,4,1,0
255495,rasha27,4003,grid-2,GRID 2,5,80.0,3.30,2013-05-27,4,1,0
255496,rasha27,3272,rocket-league,Rocket League,5,86.0,4.01,2015-07-07,17,1,0

In [32]:
filter_df['ecart'] = abs(filter_df['user_rating'] - filter_df['rawg_rating'])
filter_df

<ipython-input-32-810fe423f564>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['ecart'] = abs(filter_df['user_rating'] - filter_df['rawg_rating'])

,user_id,game_id,game_slug,game_name,user_rating,metacritic,rawg_rating,released,play_time,purchase,dummies,ecart
0,1,446900,high-rise-a-puzzle-cityscape,High Rise - A Puzzle Cityscape,4,NaN,4.00,2020-05-16,0,1,0,0.00
1,1,264830,twinfold,Twinfold,5,NaN,5.00,2018-12-05,0,1,0,0.00
2,1,58443,pocket-run-pool,Pocket-Run Pool,4,NaN,4.00,2018-05-24,0,1,0,0.00
4,1,21889,desert-fox-the-battle-of-el-alamein,Desert Fox: The Battle of El Alamein,4,NaN,4.00,2014-06-26,0,1,0,0.00
5,1,1190,imbroglio,Imbroglio,4,NaN,4.00,2016-05-18,0,1,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
255492,rasha27,5578,grid,Race Driver: Grid,5,87.0,3.67,2008-06-03,1,1,0,1.33
255493,rasha27,326292,fall-guys,Fall Guys: Ultimate Knockout,3,80.0,3.87,2020-08-04,4,1,0,0.87
255494,rasha27,2572,dirt-rally,DiRT Rally,5,86.0,3.74,2015-12-07,4,1,0,1.26
255495,rasha27,4003,grid-2,GRID 2,5,80.0,3.30,2013-05-27,4,1,0,1.70
255496,rasha27,3272,rocket-league,Rocket League,5,86.0,4.01,2015-07-07,17,1,0,0.99

In [34]:
filter_df['ecart'].sum()/len(filter_df)

0.7040204039991838