In [1]:
import numpy as np
import pandas as pd
import requests
import math

In [20]:
user_games = pd.read_csv("../raw_data/rawg_2k_50k.csv")

In [21]:
user_games.shape

(50056, 5)

In [22]:
user_games.head()

,game_id,game_name,game_slug,user_id,rating
0,2454,DOOM (2016),doom,1002,5
1,13886,STAR WARS Battlefront 2 (2005),star-wars-battlefront-ii-2,1002,3
2,50781,Sea of Thieves,sea-of-thieves,1002,3
3,8433,Halo Wars 2,halo-wars-2,1002,4
4,4358,Assassin's Creed Revelations,assassins-creed-revelations,1002,5

In [28]:
user_game_id = pd.unique(user_games['game_id'])

In [29]:
user_game_id.shape

(8043,)

In [30]:
user_game_id

array([  2454,  13886,  50781, ..., 366035,  50038,  51200])

In [3]:
games.drop([0], inplace=True)

In [4]:
games_ids = games['game_id'].tolist()

In [51]:
games_ids

[446900,
 264830,
 58443,
 51288,
 21889,
 1190,
 1175,
 326668,
 311050,
 262668,
 59052,
 58156,
 6630,
 1972,
 252219,
 58940,
 6111,
 33613,
 22515,
 1867,
 1353,
 1268,
 359798,
 6675,
 6370,
 6270,
 376790,
 305984,
 254778,
 49769,
 49332,
 7118,
 1409,
 52095,
 7987,
 2227,
 44560,
 34922,
 273,
 351827,
 31142,
 45283,
 34606,
 15680,
 1092,
 470,
 55403,
 32353,
 2463,
 192,
 29633,
 55194,
 22973,
 59144,
 5374,
 30302,
 2351,
 339,
 508,
 2710,
 25013,
 1441,
 334,
 52356,
 13748,
 13505,
 33440,
 691,
 58223,
 772,
 568,
 665,
 12922,
 375196,
 275683,
 1103,
 1596,
 60812,
 2984,
 195,
 326247,
 74114,
 32685,
 1616,
 51431,
 46738,
 455,
 25091,
 20926,
 13681,
 701,
 32062,
 6131,
 59011,
 52177,
 517,
 22728,
 16844,
 605,
 453,
 4377,
 51435,
 971,
 244698,
 1628,
 13682,
 1840,
 667,
 375199,
 23494,
 380786,
 21673,
 59894,
 5360,
 22980,
 51609,
 8042,
 21515,
 8665,
 29839,
 1515,
 19172,
 3173,
 1055,
 368,
 389,
 19399,
 22774,
 6220,
 10871,
 1822,
 428559,
 14448,
 23741,
 23419,
 19277,
 18292,
 45957,
 304216,
 97766,
 3899,
 3888,
 1905,
 2049,
 62423,
 12240,
 5873,
 47359,
 2188,
 12829,
 5561,
 19681,
 3087,
 1222,
 16122,
 49950,
 18793,
 13051,
 4267,
 20836,
 437049,
 292840,
 471027,
 16698,
 22702,
 15079,
 29826,
 20850,
 11364,
 19576,
 730,
 591,
 1602,
 995,
 4903,
 58818,
 5916,
 8098,
 304247,
 14188,
 6321,
 22510,
 1892,
 4199,
 51487,
 28203,
 557,
 46000,
 2936,
 1391,
 5978,
 2020,
 18628,
 19580,
 19437,
 20180,
 7102,
 1757,
 2060,
 964,
 4005,
 14983,
 10091,
 10370,
 16974,
 3656,
 22798,
 12074,
 23165,
 14447,
 24619,
 3545,
 50839,
 5196,
 3746,
 22344,
 326229,
 3186,
 7241,
 4490,
 1451,
 59637,
 700,
 22734,
 3871,
 881,
 437059,
 24,
 3164,
 2666,
 2570,
 5783,
 58732,
 8444,
 4356,
 17010,
 12741,
 46508,
 4519,
 30899,
 58764,
 17087,
 12073,
 798,
 5877,
 2592,
 8278,
 1249,
 27,
 17975,
 1854,
 28126,
 59197,
 43,
 5403,
 18712,
 15851,
 13566,
 3558,
 3179,
 876,
 1612,
 897,
 2639,
 2287,
 28121,
 18287,
 10050,
 28026,
 3501,
 59313,
 3268,
 326252,
 2434,
 58753,
 22513,
 17127,
 3486,
 1259,
 2518,
 1140,
 719,
 18003,
 295,
 3561,
 4397,
 1758,
 3350,
 17037,
 274762,
 4491,
 10297,
 894,
 857,
 7819,
 22511,
 11726,
 3408,
 5161,
 11974,
 2873,
 1090,
 42,
 1358,
 2093,
 15859,
 19590,
 624,
 5562,
 1774,
 28623,
 952,
 10560,
 3990,
 1682,
 15002,
 3740,
 2819,
 3853,
 2361,
 5703,
 2743,
 13535,
 1010,
 18240,
 12536,
 3254,
 5525,
 39,
 4248,
 4166,
 613,
 3696,
 4806,
 4161,
 13633,
 3636,
 4514,
 3144,
 13668,
 3612,
 19709,
 2462,
 19710,
 19103,
 278,
 23027,
 32,
 3272,
 1030,
 13537,
 4286,
 13536,
 4062,
 12020,
 5286,
 3328,
 4200,
 3498,
 305487,
 34405,
 726,
 31829,
 33383,
 87820,
 23062,
 33908,
 32229,
 56045,
 40434,
 400295,
 490430,
 9819,
 59233,
 35403,
 28542,
 48,
 30112,
 46893,
 29413,
 24138,
 27390,
 4416,
 423947,
 53251,
 36850,
 956,
 24079,
 10532,
 56123,
 19289,
 27976,
 32197,
 53239,
 53471,
 9501,
 24881,
 30243,
 27036,
 53207,
 27022,
 457729,
 4499,
 43252,
 56092,
 19046,
 43050,
 1452,
 59248,
 25924,
 5677,
 32716,
 24030,
 257255,
 39080,
 2058,
 7407,
 23599,
 27024,
 22685,
 29642,
 41115,
 24899,
 59352,
 1150,
 28581,
 3364,
 52790,
 17874,
 52369,
 339958,
 25097,
 3203,
 34744,
 3532,
 58782,
 58325,
 22512,
 30,
 29179,
 4187,
 59199,
 30445,
 887,
 54491,
 54492,
 55984,
 17676,
 447,
 14331,
 19615,
 10926,
 58385,
 4671,
 9659,
 10125,
 13909,
 19560,
 35561,
 7439,
 19397,
 5678,
 2894,
 15860,
 2767,
 19380,
 3726,
 19568,
 3850,
 274480,
 842,
 19057,
 4744,
 19056,
 4535,
 3601,
 4602,
 52939,
 29153,
 20405,
 2778,
 13820,
 4388,
 14606,
 28131,
 19410,
 4358,
 11279,
 3459,
 4581,
 51610,
 5528,
 4340,
 17857,
 28395,
 5636,
 884,
 5564,
 5565,
 21926,
 19299,
 58813,
 19452,
 4729,
 5159,
 3346,
 15858,
 18614,
 5687,
 58755,
 13913,
 20406,
 22509,
 2553,
 6617,
 2728,
 14446,
 56184,
 4123,
 3209,
 15834,
 14962,
 8146,
 11276,
 18336,
 19542,
 21265,
 58812,
 17959,
 480,
 4550,
 998,
 4440,
 28202,
 50734,
 8488,
 19365,
 28154,
 1256,
 18613,
 865,
 432,
 4639,
 906,
 3771,
 23585,
 4527,
 10989,
 1450,
 3556,
 4544,
 17572,
 2792,
 28568,
 290856,
 17576,
 12447,
 11142,
 864,
 4280,
 19301,
 108,
 11934,
 29177,
 5563,
 3387,
 11935,
 9767,
 4570,
 18080,
 2551,
 10754,
 58134,
 11936,
 19487,
 416,
 4427,
 11973,
 29028,
 7689,
 3192,
 58175,
 4459,
 2454,
 11859,
 28,
 4291,
 802,
 5679,
 150724,
 47782,
 57224,
 31033,
 22792,
 30025,
 29373,
 50616,
 19287,
 19300,
 44265,
 19430,
 17620,
 19359,
 13833,
 17473,
 4414,
 4003,
 13554,
 430,
 50,
 944,
 955,
 1236,
 10898,
 47,
 137,
 49,
 8349,
 47137,
 32527,
 31822,
 13679,
 35702,
 30814,
 46533,
 28974,
 15512,
 16743,
 30016,
 16739,
 14004,
 29696,
 19367,
 19298,
 3873,
 43454,
 57967,
 32734,
 10158,
 40086,
 28501,
 185388,
 53432,
 20,
 28218,
 19476,
 40214,
 28478,
 18698,
 51551,
 3857,
 181,
 22828,
 3822,
 28604,
 452634,
 19509,
 299561,
 25829,
 442847,
 4507,
 3855,
 3485,
 4666,
 49428,
 1692,
 19519,
 4493,
 18304,
 19701,
 17830,
 17831,
 5265,
 10234,
 1713,
 12893,
 4052,
 28422,
 21759,
 295001,
 47351,
 1258,
 52178,
 52998,
 4700,
 14346,
 52997,
 19646,
 54718,
 2483,
 17604,
 7442,
 58890,
 20709,
 19345,
 17573,
 16264,
 58735,
 442854,
 1430,
 54285,
 6885,
 16262,
 39039,
 4023,
 16263,
 19458,
 58698,
 1165,
 3767,
 19628,
 19627,
 23600,
 320,
 40936,
 28608,
 14929,
 3413,
 674,
 3223,
 3933,
 4154,
 54,
 10389,
 17945,
 244716,
 16723,
 19635,
 4466,
 10393,
 5390,
 4962,
 18726,
 16649,
 19655,
 14422,
 28589,
 4923,
 29,
 13079,
 28631,
 122,
 28615,
 13387,
 12884,
 4013,
 19633,
 14072,
 50781,
 16787,
 715,
 28261,
 3748,
 5298,
 11970,
 13469,
 29338,
 17599,
 3265,
 50778,
 19429,
 19592,
 4439,
 19451,
 3052,
 22121,
 10419,
 3635,
 250,
 1789,
 19491,
 12320,
 3697,
 4094,
 19375,
 4000,
 14690,
 42895,
 28559,
 19569,
 14016,
 13194,
 28172,
 18183,
 3028,
 16113,
 1169,
 51325,
 21924,
 2733,
 10061,
 3631,
 3497,
 18241,
 257201,
 3757,
 3474,
 3168,
 58616,
 28153,
 13627,
 13461,
 923,
 3876,
 13305,
 46889,
 2235,
 10065,
 3687,
 1416,
 10243,
 3017,
 13910,
 3747,
 3841,
 17540,
 5583,
 41494,
 4828,
 4386,
 17822,
 4332,
 4252,
 10035,
 3287,
 3070,
 3439,
 51898,
 8481,
 10885,
 379505,
 43052,
 9847,
 52042,
 60540,
 20705,
 2695,
 286536,
 17400,
 2168,
 428890,
 280620,
 58201,
 60894,
 10572,
 349735,
 50223,
 45618,
 13961,
 3783,
 372679,
 10273,
 316895,
 12350,
 58515,
 60881,
 9907,
 284699,
 32088,
 12459,
 366883,
 36472,
 42957,
 62351,
 21171,
 14157,
 22782,
 40002,
 30813,
 9972,
 3755,
 245719,
 3614,
 9646,
 3712,
 349634,
 288671,
 42277,
 14627,
 3289,
 376934,
 10570,
 30891,
 9632,
 53435,
 32674,
 9809,
 21385,
 4048,
 409543,
 60685,
 42405,
 4266,
 18114,
 58285,
 16631,
 4214,
 3523,
 40445,
 10702,
 58819,
 13576,
 11416,
 12710,
 3538,
 48930,
 3847,
 23073,
 22962,
 24182,
 12177,
 59319,
 3484,
 349677,
 17740,
 19532,
 17621,
 17884,
 17525,
 17512,
 17704,
 3784,
 17836,
 53461,
 17142,
 22391,
 12075,
 20368,
 17648,
 31713,
 17669,
 14552,
 9818,
 438599,
 17866,
 17593,
 13160,
 14236,
 14103,
 17144,
 13686,
 449164,
 46180,
 14104,
 13532,
 17797,
 17143,
 16406,
 14102,
 17141,
 3625,
 17942,
 17786,
 17140,
 21280,
 14741,
 42144,
 29203,
 17943,
 17065,
 270730,
 49268,
 17254,
 7087,
 56165,
 14696,
 22441,
 552,
 17139,
 9801,
 17860,
 298413,
 56088,
 19478,
 19761,
 524,
 15993,
 3248,
 10311,
 6905,
 17211,
 42714,
 52825,
 10082,
 6627,
 4447,
 17891,
 69,
 648,
 14106,
 10847,
 379453,
 3372,
 57519,
 52623,
 264721,
 3943,
 21876,
 127659,
 1201,
 ...]

In [6]:
type(games_ids)

list

In [15]:
URL = "https://api.rawg.io/api/games?dates=2019-06-01,2021-03-03&ordering=-rating"

In [115]:
def get_games(game_id):
    
    try:
#         api_key="58eeb730ca1a47e8aa9d130c3127d412"
        url=f"https://api.rawg.io/api/games/{game_id}"
        response = requests.get(url)
        data = response.json()

    #         this is to transfer the list of dict into a string to stock in one cell:
        rawg_ratings = []
        for rating in data["ratings"]:
            rawg_ratings.append(f"{rating['id']}|{rating['title']}|{rating['count']}|{rating['percent']}")
#         print(', '.join(rawg_ratings))

    #         this is to get the list of platforms availble for each games:
        game_platforms = []
        for platform in data["platforms"]:
            game_platforms.append(f"{platform['platform']['id']}|{platform['platform']['name']}")

#         print(', '.join(game_platforms))

        game_genres = []
        for genre in data["genres"]:
            game_genres.append(genre['name'])
#         print(', '.join(game_genres))

        game_tags = []
        for tag in data['tags']:
            game_tags.append(tag['name'])
#         print(', '.join(game_genres))

        developers = []
        if data["developers"]:
            for developer in data["developers"]:
                developers.append(f"{developer['id']}|{developer['name']}")
#             print(', '.join(developers))

        publishers = []
        if data["publishers"]:
            for publisher in data["publishers"]:
                publishers.append(f"{publisher['id']}|{publisher['name']}")
#             print(', '.join(publishers))

        new_games.append({"game_id":game_id,
                           "slug": data["slug"],
                           "name":data["name"],
                           "description":data["description"],
                           "released":data["released"],
                           "rating":data["rating"],
                           "detail_ratings":', '.join(rawg_ratings),
                           "ratings_count":data["ratings_count"],
                           "suggestions_count":data["suggestions_count"],
                           "game_series_count":data["game_series_count"],
                           "reviews_count":data["reviews_count"],
                           "metacritic":data["metacritic"],
                           "game_platforms":', '.join(game_platforms),
                           "game_genres":', '.join(game_genres),
                           "game_tags":', '.join(game_tags),
                           "developers": ', '.join(developers),
                           "publishers": ', '.join(publishers)})
              
        print(f"game-{game_id}-{data['name']} has added to list")
    
    except:
        print ("no games")

In [17]:
3436 in games_ids

True

In [52]:
for i in np.arange(1,10):
    print (i)

1
2
3
4
5
6
7
8
9

In [40]:
pages = (206510 / 20)+1
pages

10326.5

In [111]:
rawg_games=[]
for i in np.arange(10,):
    url= f"https://api.rawg.io/api/games?dates=2019-06-01,2021-03-03&page={1}"
    response = requests.get(URL)
    data = response.json()
    scap_games = data['results']
    for game in scap_games:
        id = int(game['id'])
        if not (id in games_ids):
            rawg_games.append(id)

339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382
339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382

In [116]:
new_games=[]
for g in rawg_games:
    get_games(g)

game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list
game-406445-Wide Ocean Big Jacket has added to list
game-397523-Sweet Dance has added to list
game-432857-Cha Cha Slide has added to list
game-379496-Steven Universe: Unleash the Light has added to list
game-399411-AI Dungeon has added to list
game-487916-Super Mario 3D World + Bowser’s Fury has added to list
game-387303-Ray Eager has added to list
game-28159-HUNTDOWN has added to list
game-503378-Friday Night Funkin' has added to list

In [119]:
df_new_games=pd.DataFrame(new_games)

In [120]:
df_new_games.to_csv('../raw_data/rawg_games.csv', index = False, mode = 'a', header=False)

In [113]:
406445 in games_ids

False

In [37]:
def scap_page(url):
    response = requests.get(URL)
    data = response.json()
    scap_games = data['results']
    for game in scap_games:
        id = int(game['id'])
        if id in games_ids == False:
            get_games(id)

In [48]:
response = requests.get(URL)
data = response.json()
scap_games = data['results']
rawg_games=[]
for game in scap_games:
    id = int(game['id'])
    print(id)
    if id in games_ids == False:
        get_games(id)

339958
406445
397523
432857
379496
399411
259801
408286
487916
452646
274755
387303
442839
28159
58550
503378
366889
452648
28199
262382

In [49]:
response

In [50]:
rawg_games

[]

In [ ]:
get_games(31033)

In [ ]:
pd.DataFrame.from_dict(rawg_games)

In [ ]:
counter = 0
for game_id in games:
    counter += 1
    get_games(game_id)
    print(counter)

In [ ]:
rawg_games_df = pd.DataFrame.from_dict(rawg_games)

In [ ]:
rawg_games_df

In [ ]:
rawg_games_df.to_csv('../raw_data/rawg_games.csv')

In [ ]:
games = pd.read_csv('../raw_data/rawg_games.csv')

In [ ]:
games.set_index('name')

In [ ]:
games.to_csv('../raw_data/rawg_games.csv',index=False)